version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: osj_postgres
    environment:
      POSTGRES_USER: osj
      POSTGRES_PASSWORD: osj
      POSTGRES_DB: osj
    ports:
      - "5432:5432"
    volumes:
      - pg_data_osj:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osj -d osj"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: osj_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

volumes:
  pg_data_osj:
